source 'https://github.com/ietstudio/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'
# use_frameworks!

target 'AdvertiseChartBoost_Example' do
  pod 'AdvertiseChartBoost', :path => '../'

  target 'AdvertiseChartBoost_Tests' do
    inherit! :search_paths

    
  end
end
